
title: Modeling Language Engineering (MLE)

social-network-links:
  email: "mle@inria.fr"
  twitter: "MleWorkshop"

description: >- # this means to ignore newlines until "baseurl:"
  The Modeling Language Engineering (MLE) workshop
  aims at bringing together researchers and practitioners 
  working on modeling language engineering.
  It is a meeting opportunity for Software Language Engineering (SLE) enthusiasts
  within the software modeling community.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://mleworkshop.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

navbar-links:
  About: "/"
  Editions:
    - MLE2024: "editions/mle2024"
    - MLE2023: "editions/mle2023"
    - MLE2022: "editions/mle2022"
    - MLE2021: "editions/mle2021"
    - MLE2020: "editions/mle2020"
    - MLE2019: "http://gemoc.org/events/mle2019"
  Steering Committee: "steeringcommittee"

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "./logo.drawio.png" 

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true


#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
# theme: minima
theme: beautiful-jekyll-theme
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - bundle
  - _site
  - vendor

permalink: /:year-:month-:day-:title/
